### ISSUE TITLE
XMLRenderer tries to import StringIO from rest_framework.compat

### ISSUE THREAD

**Issue by brandoncazander** [jpadilla/django-rest-framework-xml#3]
When trying to use XMLRenderer, an ImportError is raised:

```ImportError: cannot import name StringIO```

The custom StringIO has [been removed](https://github.com/tomchristie/django-rest-framework/commit/d54c67d79d0f5661ef33d860efe80a4272e22b3e) from rest_framework.compat.

**Comment by jpadilla** [comment]
@brandoncazander yeah good catch. Can you put a PR together to fix it? If not I'll try to get to it later today or tomorrow.
