### ISSUE TITLE
LICENSE vs setup.py

### ISSUE THREAD

**Issue by jayvdb** [jpadilla/django-rest-framework-xml#37]
For many of your projects, especially the django projects which I am trying to package for openSUSE, the setup.py says `BSD`, but the LICENSE file is `ISC`.

Could you clarify which one you intend, and fix the conflict (or I can submit PRs where I find the problem if I know which one is your intention).

**Comment by jpadilla** [comment]
@jayvdb that's a good catch, thanks for bringing it up. I think the intention for these projects that came from the django rest framework project is to be BSD https://choosealicense.com/licenses/bsd-3-clause/ and is what we're also showing on pypi https://pypi.org/project/djangorestframework-xml/

Pull requests are welcome 😃

**Comment by jayvdb** [comment]
Done for the repos under `https://github.com/jpadilla/` .  I guess they are based on your cookiecutter template, so that likely needs updating.  Happy to do some more if you have others located in orgs somewhere.

**Comment by jayvdb** [comment]
Please also process the other PRs listed here, as I would like to package those also.

**Comment by jayvdb** [comment]
Thanks a bundle!
