### ISSUE TITLE
pip in cmd reurns error message.

### ISSUE THREAD

**Issue by CheboHorpes** [jpadilla/django-rest-framework-xml#40]
I just installed python 3.7.4 on windows 10 and run pip -v but it returns an error message. I am new and I am stuck, what could be the problem?
![pip error](https://user-images.githubusercontent.com/42945578/65154188-57067280-da2b-11e9-8fc1-70312142e56b.png)

**Comment by jpadilla** [comment]
Hi there! I don't currently see anything related to this package in that stack trace. Closing for now. Feel free to post any update or follow up here.
