### ISSUE TITLE
django 3 support

### ISSUE THREAD

**Issue by marco-silva0000** [jpadilla/django-rest-framework-xml#45]
As stated with the deprecation warnings, `from django.utils import six`is now not supported in django 3, released 3 days ago. This library is using that util and is therefore not compatible.

the same problem is affecting other libraries, as you can see [here](https://github.com/jazzband/django-constance/issues/341).

can be fix by adding `six` as a dependency.

**Comment by marco-silva0000** [comment]
I had not seen PR #44 because I had a filter for issues only, they both fix the same issue though.

Mine has requirements and tox.ini changes, but maybe it's better to have a separate issue and patch for those changes, as it might be incomplete.

**Comment by jpadilla** [comment]
Hey @marco-silva0000 thanks for the help with this. I'm thinking we would benefit from updating this project to dropping support for Python 2 and dropping support for old DRF versions, and testing just against DRF 3.11.

Thoughts? Any interest in leading this?

**Comment by marco-silva0000** [comment]
Completely agree. I don't have much experience with tox and all of that but will look into it. That should be a separate issue right?

**Comment by jpadilla** [comment]
@marco-silva0000 yeah sure, thanks!

**Comment by danieluisilva** [comment]
Hi! Any update? :)

**Comment by jpadilla** [comment]
Closed by #53
