### ISSUE TITLE
List of items

### ISSUE THREAD

**Issue by volodchenkov** [jpadilla/django-rest-framework-xml#5]
Can you add support for list of items like:

``` xml
<root>
<list>
<list-item>
<id>1</id>
<name>test</name>
</list-item>
</list>
</root>
```

**Comment by jpadilla** [comment]
@volodchenkov maybe best thing would be for you to create your own renderer based on `XMLRenderer`.

**Comment by kyleobrien91** [comment]
@volodchenkov - I don't think this issue is going to result in anything actionable. I think that #11 is a bit more of a better outline for @Charlemagne3 's PR.
