### ISSUE TITLE
Can this use lxml?

### ISSUE THREAD

**Issue by savingschampion** [jpadilla/django-rest-framework-xml#6]
For large responses, using something like lxml to render the xml could cut rendering time.

**Comment by jpadilla** [comment]
@savingschampion I don't see why we couldn't use lxml if it was available falling back to default implementation. Want to tackle it and submit a PR?

**Comment by kyleobrien91** [comment]
@savingschampion - if you find yourself inclined to contribute a PR for this, please reopen an issue with a spec at that point. Thanks!
